// <auto-generated />
namespace Agroin4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class upda_logadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upda_logadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201707120722213_upda_logadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
